extends Node

var MIN_NUMBER_TILE = 1;
var MAX_NUMBER_TILE = 10;

var DEFAULT_TILE_DRAWN = 7;

var DEFAULT_TILE_COUPLE_SLOTS = 4;

# ANIMATION

var SHORT_TRANSITION_DURATION = 0.05;
var DEFAULT_GROW_FACTOR = 1.2;
