extends Node

var MIN_NUMBER_TILE = 1;
var MAX_NUMBER_TILE = 10;

var DEFAULT_TILE_DRAWN = 7;
var DEFAULT_TILE_COUPLE_SLOTS = 4;
var BASE_TURN_NUMBER = 5;

# CARDS
var DECK_START_SIZE = 4;
var MAX_NUMBER_CARDS_DRAWN = 3;
var MAX_NUMBER_CARDS_IN_HAND = 5;

# SHOP
var DEFAULT_TILE_AMOUNT_IN_SHOP = 3;
var DEFAULT_BUNDLE_AMOUNT_IN_SHOP = 2;
var DEFAULT_CARD_AMOUNT_IN_SHOP = 3;
var NUMBER_TILE_BASE_PRICE = 2;

# MONEY 
var BASE_MONEY_REWARD = 3;
var MONEY_PER_TURN_LEFT = 1;
var MONEY_BOUNTY_FOR_PERFECT = 5;

# COUNTDOWN

var MIN_COUNTDOWN_VALUE = 50;
var MAX_COUNTDOWN_VALUE = 100;

# ANIMATION

var SHORT_TRANSITION_DURATION = 0.05;
var DEFAULT_TRANSITION_DURATION = 0.75;
var DEFAULT_GROW_FACTOR = 1.2;

# ALIENS
var DEFAULT_ALIEN = 0;
