extends Node

var MIN_NUMBER_TILE = 1;
var MAX_NUMBER_TILE = 10;

var DEFAULT_TILE_DRAWN = 7;
var MAX_NUMBER_CARDS = 3;
var DEFAULT_TILE_COUPLE_SLOTS = 4;
var BASE_TURN_NUMBER = 5;
# COUNTDOWN

var MIN_COUNTDOWN_VALUE = 50;
var MAX_COUNTDOWN_VALUE = 100;

# ANIMATION

var SHORT_TRANSITION_DURATION = 0.05;
var DEFAULT_TRANSITION_DURATION = 1.;
var DEFAULT_GROW_FACTOR = 1.2;
