extends Node

signal play_phase_started
signal execution_phase_started
signal play_phase_submitted

signal tile_drawn

signal on_win 
signal on_loss

signal operator_tile_selected
signal number_tile_selected
signal operator_tile_unselected
signal number_tile_unselected
signal on_tile_couple_executed
